name: first

on: push

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
            - name: Step one
              run: date
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
            - name: Step one
              run: DATE
    job3:
        name: Third Job
        runs-on: macos-latest
        steps:
            - name: Step one
              run: date
    job4:
        name: fourth Job
        runs-on: ubuntu-latest
        needs: [job1, job2, job3]
        steps:
            - name: Step one
              run: date